version: '3.9'

services:
  web:
    build:
      context: .
    environment:
      - REDIS_HOST=redis
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - redis

  redis:
    image: redis:latest

  celery:
    build:
      context: .
    command: celery -A myblog worker -l info
    volumes:
      - .:/usr/src/app
    depends_on:
      - web
      - redis

  celery-beat:
    build:
      context: .
    command: celery -A myblog beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/usr/src/app