version: '3.9'

services:
  web:
    build:
      context: .
    environment:
      - REDIS_HOST=redis
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - redis

  redis:
    image: redis:latest