# Generated by Django 4.1.7 on 2023-03-25 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Changelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('changes', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('text', models.TextField(default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='app',
            old_name='github_url',
            new_name='img1_url',
        ),
        migrations.RenameField(
            model_name='app',
            old_name='img_url',
            new_name='img2_url',
        ),
        migrations.RemoveField(
            model_name='app',
            name='description',
        ),
        migrations.AddField(
            model_name='app',
            name='img3_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='app',
            name='link1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='app',
            name='link2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='app',
            name='link3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='app',
            name='logo_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='app',
            name='text',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='app',
            name='views_count',
            field=models.CharField(default=7, max_length=50),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('img_url', models.CharField(blank=True, max_length=200)),
                ('short_desc', models.CharField(max_length=200)),
                ('text', models.TextField(default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('app_url', models.CharField(blank=True, max_length=200)),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.comment')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.tag')),
            ],
            options={
                'verbose_name': 'App',
                'verbose_name_plural': 'Apps',
            },
        ),
        migrations.AddField(
            model_name='app',
            name='changelog',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.changelog'),
        ),
    ]
