# Generated by Django 4.1.7 on 2023-03-26 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_comments_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='changelog',
        ),
        migrations.AddField(
            model_name='changelog',
            name='app',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.app'),
        ),
    ]
