# Generated by Django 4.1.7 on 2023-03-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_app_changelog_changelog_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='slug',
            field=models.CharField(default='hui', max_length=100),
            preserve_default=False,
        ),
    ]
