# Generated by Django 4.1.7 on 2023-03-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_app_check_status_url_app_is_active_app_short_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
