# Generated by Django 4.1.7 on 2023-03-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='views_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='views_count',
            field=models.IntegerField(),
        ),
    ]
