# Generated by Django 4.1.7 on 2023-04-05 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_options_alter_app_views_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='views_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='views_count',
        ),
    ]
