# Generated by Django 4.1.7 on 2023-04-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={'ordering': ['-views__hits'], 'verbose_name': 'App', 'verbose_name_plural': 'Apps'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pk'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AddField(
            model_name='app',
            name='background_img_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
