# Generated by Django 4.1.7 on 2023-04-10 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.section'),
        ),
    ]
